/**
 * MCP Tool Executor
 * 
 * Executes MCP tools directly via API-Server client (without going through React UI SDK).
 * This enables headless mode and reduces latency.
 */

import { apiClient } from './apiClient.js';
import { getConfig } from '../config/index.js';
import { logger } from './logger.js';

// Tool execution context
export interface ToolExecutionContext {
  sessionId?: string;
  userId?: string;
  userToken?: string; // User's JWT token for API-Server authentication
}

// Tool execution result
export interface ToolExecutionResult {
  success: boolean;
  data?: unknown;
  error?: string;
  hint?: string;
  reason?: string;
  suggestedAction?: string;
  suggestedArgs?: Record<string, unknown>;
  sessionId?: string; // New session ID if created
}

// Reserved keys that should not be included in element data
const RESERVED_KEYS = new Set([
  'elementType',
  'element_type',
  'sessionId',
  'session_id',
  'options',
  'identifier',
  'data',
  'arg',
  'argument',
  'args',
  'params',
  'parameters',
  'fileName',
  'newFileName',
  'fileType',
  'file',
  'method',
  'tolerance',
  'maxIterations',
  'max_iterations',
  'lossless_network',
]);

// Keys that may contain element data (in order of priority)
const DATA_CONTAINER_KEYS = ['data', 'arg', 'argument', 'args', 'params', 'parameters'];

// Fields that must be strings (identifier fields that Rust expects as String type)
const STRING_IDENTIFIER_FIELDS = new Set(['loadid', 'machid', 'ckt', 'shntid', 'loadtype']);

// Fields that can be auto-generated by the backend if not provided
const AUTO_GENERATABLE_ID_FIELDS = new Set(['loadid', 'machid', 'ckt', 'shntid']);

// Element schemas (defined independently for server-side execution)
const ELEMENT_SCHEMAS: Record<string, {
  identifierKeys: string[];
  dataKeys: string[];
  description: string;
}> = {
  bus: {
    identifierKeys: ['ibus'],
    dataKeys: ['baskv', 'ide', 'area', 'zone', 'vm', 'va'],
    description: 'Bus element',
  },
  load: {
    identifierKeys: ['ibus', 'loadid'],
    dataKeys: ['pl', 'ql', 'stat'],
    description: 'Load element',
  },
  generator: {
    identifierKeys: ['ibus', 'machid'],
    dataKeys: ['pg', 'qg', 'qt', 'qb', 'stat', 'vg'],
    description: 'Generator element',
  },
  acline: {
    identifierKeys: ['ibus', 'jbus', 'ckt'],
    dataKeys: ['rpu', 'xpu', 'bpu', 'stat'],
    description: 'AC Line element',
  },
  transformer: {
    identifierKeys: ['ibus', 'jbus', 'kbus', 'ckt'],
    dataKeys: ['rpu', 'xpu', 'stat'],
    description: 'Transformer element',
  },
  shunt: {
    identifierKeys: ['ibus', 'shntid'],
    dataKeys: ['gpu', 'bpu', 'stat'],
    description: 'Shunt element',
  },
  fixshunt: {
    identifierKeys: ['ibus', 'shntid'],
    dataKeys: ['stat', 'gl', 'bl'],
    description: 'Fixed shunt element. Gl is conductance (MW), Bl is susceptance (MVar).',
  },
  swshunt: {
    identifierKeys: ['ibus', 'shntid'],
    dataKeys: ['modsw', 'adjm', 'stat', 'vswhi', 'vswlo', 'swreg', 'nreg', 'rmpct', 'rmidnt', 'binit', 's1', 'n1', 'b1', 's2', 'n2', 'b2', 's3', 'n3', 'b3', 's4', 'n4', 'b4', 's5', 'n5', 'b5', 's6', 'n6', 'b6', 's7', 'n7', 'b7', 's8', 'n8', 'b8'],
    description: 'Switched shunt element. Supports voltage control with up to 8 blocks of steps.',
  },
};

/**
 * Coerce identifier fields to strings if they are passed as numbers.
 */
function coerceStringFields(data: Record<string, unknown>): Record<string, unknown> {
  const result = { ...data };
  for (const key of Array.from(STRING_IDENTIFIER_FIELDS)) {
    if (key in result && result[key] != null && typeof result[key] !== 'string') {
      result[key] = String(result[key]);
    }
  }
  return result;
}

/**
 * Normalize sessionId from various formats
 */
function normalizeSessionId(v: unknown): string | undefined {
  if (v == null) return undefined;
  if (typeof v === 'string') return v;
  if (typeof v === 'object' && !Array.isArray(v)) {
    const o = v as Record<string, unknown>;
    return (o.sessionId ?? o.session_id) as string | undefined;
  }
  return undefined;
}

/**
 * Normalize elementType from args
 */
function normalizeElementType(args: Record<string, unknown>): string | undefined {
  const et = args.elementType ?? args.element_type;
  if (et != null && typeof et === 'string') return et;
  return undefined;
}

/**
 * Extract element data from args.
 */
function extractElementData(args: Record<string, unknown>, elementType: string): Record<string, unknown> {
  // Check all possible data container keys
  for (const containerKey of DATA_CONTAINER_KEYS) {
    const container = args[containerKey];
    if (container && typeof container === 'object' && !Array.isArray(container)) {
      logger.debug(`[ToolExecutor] Found data in container key: ${containerKey}`);
      return container as Record<string, unknown>;
    }
  }

  // Otherwise, extract all non-reserved keys from args
  const schema = ELEMENT_SCHEMAS[elementType];
  const idKeys = new Set(schema?.identifierKeys ?? []);
  const dataKeys = new Set(schema?.dataKeys ?? []);
  
  const data: Record<string, unknown> = {};
  
  for (const [key, value] of Object.entries(args)) {
    if (RESERVED_KEYS.has(key)) continue;
    if (idKeys.has(key) || dataKeys.has(key) || !RESERVED_KEYS.has(key)) {
      if (value !== undefined && value !== null) {
        data[key] = value;
      }
    }
  }
  
  return data;
}

/**
 * Get identifier from args based on element schema
 */
function identifierFromArgs(args: Record<string, unknown>, elementType: string): Record<string, unknown> | undefined {
  const schema = ELEMENT_SCHEMAS[elementType];
  const idKeys = schema?.identifierKeys ?? [];
  if (!idKeys.length) return undefined;
  
  const out: Record<string, unknown> = {};
  for (const k of idKeys) {
    if (args[k] !== undefined && args[k] !== null) out[k] = args[k];
  }
  return Object.keys(out).length ? out : undefined;
}

/**
 * Summarize a contingency-analysis report when the raw payload would be too
 * large to feed to the LLM. Threshold ~64 KB of JSON; under that we pass the
 * report through verbatim. Over that, we surface counts and the top few
 * violation-causing contingencies. Exact summarization can be refined later
 * once we know what the LLM actually needs.
 */
function summarizeContingencyReport(report: unknown): unknown {
  if (report == null || typeof report !== 'object') return report;
  const raw = JSON.stringify(report);
  if (raw.length <= 64 * 1024) return report;

  const r = report as Record<string, any>;
  const contingencies = Array.isArray(r.contingencies)
    ? r.contingencies
    : Array.isArray(r.results)
      ? r.results
      : [];
  const withViolations = contingencies.filter((c: any) =>
    Array.isArray(c?.violations) ? c.violations.length > 0 : false,
  );
  const top = withViolations
    .slice()
    .sort(
      (a: any, b: any) =>
        (b.violations?.length ?? 0) - (a.violations?.length ?? 0),
    )
    .slice(0, 10);

  return {
    truncated: true,
    rawBytes: raw.length,
    summary: {
      totalContingencies: contingencies.length,
      contingenciesWithViolations: withViolations.length,
      topContingencies: top.map((c: any) => ({
        id: c.id ?? c.name ?? c.label,
        violationCount: c.violations?.length ?? 0,
      })),
    },
    hint: 'Report was too large to return in full. Ask the user which contingency to drill into; fetch a specific result via the study-result UI if needed.',
  };
}

/**
 * Execute an MCP tool by name
 */
export async function executeMCPTool(
  name: string,
  args: Record<string, unknown>,
  context?: ToolExecutionContext
): Promise<ToolExecutionResult> {
  const config = getConfig();
  const userId = context?.userId || config.serviceAuth.defaultUserId;
  const userToken = context?.userToken;
  const sessionId = context?.sessionId || normalizeSessionId(args.sessionId ?? args.session_id);

  logger.info('[ToolExecutor] Executing tool', { name, sessionId, userId, hasToken: !!userToken });

  try {
    switch (name) {
      // ===========================================
      // SESSION MANAGEMENT
      // ===========================================
      
      case 'getElementSchema': {
        const elementType = normalizeElementType(args) ?? '';
        const schema = ELEMENT_SCHEMAS[elementType];
        if (!schema) {
          return { 
            success: false, 
            error: `Unknown element type: ${elementType}`,
            hint: 'Available types: bus, load, generator, acline, transformer, fixshunt, swshunt'
          };
        }
        return { success: true, data: { elementType, ...schema } };
      }

      case 'createSession': {
        const result = await apiClient.createSession(userId, userToken);
        if (!result.success) {
          return { success: false, error: result.error };
        }
        // Return the new session ID for tracking
        const newSessionId = (result.data as any)?.session_id;
        return { success: true, data: result.data, sessionId: newSessionId };
      }

      case 'createSessionFromFile': {
        const fileName = args.fileName as string;
        if (!fileName) {
          return { success: false, error: 'fileName is required' };
        }
        const result = await apiClient.createSessionFromFile(fileName, userId, userToken);
        if (!result.success) {
          return { success: false, error: result.error };
        }
        // Return the new session ID for tracking
        const newSessionId = (result.data as any)?.session_id;
        return { success: true, data: result.data, sessionId: newSessionId };
      }

      case 'getSessionInfo': {
        if (!sessionId) {
          return { success: false, error: 'sessionId is required' };
        }
        const result = await apiClient.getSession(sessionId, userId, userToken);
        if (!result.success) {
          return { success: false, error: result.error };
        }
        return { success: true, data: result.data };
      }

      case 'deleteSession': {
        if (!sessionId) {
          return { success: false, error: 'sessionId is required' };
        }
        const result = await apiClient.deleteSession(sessionId, userId, userToken);
        if (!result.success) {
          return { success: false, error: result.error };
        }
        return { success: true, data: result.data };
      }

      // ===========================================
      // NETWORK OPERATIONS
      // ===========================================

      case 'getNetwork': {
        if (!sessionId) {
          return { success: false, error: 'sessionId is required' };
        }
        const result = await apiClient.getNetwork(sessionId, userId, userToken);
        if (!result.success) {
          return { success: false, error: result.error };
        }
        
        // Filter by element type if specified
        const elementType = normalizeElementType(args);
        if (elementType && result.data) {
          const networkData = result.data as Record<string, unknown>;
          const elementKey = `${elementType}s`;
          if (networkData[elementKey]) {
            return { success: true, data: { [elementType]: networkData[elementKey] } };
          }
        }
        
        return { success: true, data: result.data };
      }

      case 'addElement': {
        if (!sessionId) {
          return { success: false, error: 'sessionId is required' };
        }
        const elementType = normalizeElementType(args) ?? '';
        const schema = ELEMENT_SCHEMAS[elementType];
        if (!schema) {
          return { 
            success: false, 
            error: `Unknown element type: ${elementType}`,
            hint: 'Available types: bus, load, generator, acline, transformer, fixshunt, swshunt'
          };
        }
        
        const idKeys = schema.identifierKeys;
        const rawData = extractElementData(args, elementType);
        
        if (Object.keys(rawData).length === 0) {
          return {
            success: false,
            error: `Missing required 'data' parameter for addElement`,
            hint: `You MUST provide element data. Call getElementSchema('${elementType}') first.`,
          };
        }
        
        const data = coerceStringFields(rawData);
        
        // Validate identifier keys (except auto-generatable ones)
        const missingKeys = idKeys.filter((k) => {
          const isMissing = data[k] === undefined || data[k] === null;
          const isAutoGeneratable = AUTO_GENERATABLE_ID_FIELDS.has(k);
          return isMissing && !isAutoGeneratable;
        });
        
        if (missingKeys.length > 0) {
          return {
            success: false,
            error: `Missing required identifier keys for ${elementType}: ${missingKeys.join(', ')}`,
            hint: `Please provide values for: ${missingKeys.join(', ')}`,
          };
        }
        
        // Get the primary identifier (first id key, usually ibus)
        const identifier: Record<string, unknown> = {};
        for (const k of idKeys) {
          if (data[k] !== undefined && data[k] !== null) {
            identifier[k] = data[k];
          }
        }
        
        const result = await apiClient.editElement(sessionId, elementType, 'add', data, identifier, userId, userToken);
        
        if (!result.success) {
          // Parse error for helpful hints
          const errorMsg = result.error || '';
          if (errorMsg.includes('already exists')) {
            return {
              success: false,
              error: errorMsg,
              reason: 'element_already_exists',
              hint: `This ${elementType} already exists. Use a different identifier.`,
            };
          }
          return { success: false, error: errorMsg };
        }
        return { success: true, data: result.data };
      }

      case 'modifyElement': {
        if (!sessionId) {
          return { success: false, error: 'sessionId is required' };
        }
        const elementType = normalizeElementType(args) ?? '';
        const schema = ELEMENT_SCHEMAS[elementType];
        if (!schema) {
          return { success: false, error: `Unknown element type: ${elementType}` };
        }
        
        const idKeys = schema.identifierKeys;
        const identifier = coerceStringFields(
          (args.identifier as Record<string, unknown>) ?? identifierFromArgs(args, elementType) ?? {}
        );
        
        // For modify, ALL identifier keys are required
        const missingKeys = idKeys.filter((k) => identifier[k] === undefined || identifier[k] === null);
        if (missingKeys.length > 0) {
          return {
            success: false,
            error: `Missing required identifier keys for modifyElement: ${missingKeys.join(', ')}`,
            hint: `For modify operations, ALL identifier fields must be provided.`,
          };
        }
        
        const data = args.data ? coerceStringFields(args.data as Record<string, unknown>) : {};
        
        const result = await apiClient.editElement(sessionId, elementType, 'modify', data, identifier, userId, userToken);
        
        if (!result.success) {
          const errorMsg = result.error || '';
          if (errorMsg.includes('not found') || errorMsg.includes('does not exist')) {
            return {
              success: false,
              error: errorMsg,
              reason: 'element_not_found',
              hint: `This ${elementType} does not exist. Use addElement() to create it first.`,
              suggestedAction: 'addElement',
              suggestedArgs: { elementType, data: { ...identifier, ...data } },
            };
          }
          return { success: false, error: errorMsg };
        }
        return { success: true, data: result.data };
      }

      case 'deleteElement': {
        if (!sessionId) {
          return { success: false, error: 'sessionId is required' };
        }
        const elementType = normalizeElementType(args) ?? '';
        const schema = ELEMENT_SCHEMAS[elementType];
        if (!schema) {
          return { success: false, error: `Unknown element type: ${elementType}` };
        }
        
        const idKeys = schema.identifierKeys;
        const identifier = coerceStringFields(
          (args.identifier as Record<string, unknown>) ?? identifierFromArgs(args, elementType) ?? {}
        );
        
        // For delete, ALL identifier keys are required
        const missingKeys = idKeys.filter((k) => identifier[k] === undefined || identifier[k] === null);
        if (missingKeys.length > 0) {
          return {
            success: false,
            error: `Missing required identifier keys for deleteElement: ${missingKeys.join(', ')}`,
            hint: `For delete operations, ALL identifier fields must be provided.`,
          };
        }
        
        // Delete by setting stat = 0 or calling delete endpoint
        const result = await apiClient.editElement(sessionId, elementType, 'delete', {}, identifier, userId, userToken);
        
        if (!result.success) {
          const errorMsg = result.error || '';
          if (errorMsg.includes('not found') || errorMsg.includes('does not exist')) {
            return {
              success: false,
              error: errorMsg,
              reason: 'element_not_found',
              hint: `This ${elementType} does not exist.`,
            };
          }
          return { success: false, error: errorMsg };
        }
        return { success: true, data: result.data };
      }

      // ===========================================
      // POWER FLOW OPERATIONS
      // ===========================================

      case 'solveFlow': {
        if (!sessionId) {
          return { success: false, error: 'sessionId is required' };
        }
        const method = (args.method as string) || 'fnsl';
        const result = await apiClient.calculatePowerFlow(sessionId, {
          method,
          area_interchange_adjustment: args.area_interchange_adjustment as string | undefined,
        }, userId, userToken);
        if (!result.success) {
          return { success: false, error: result.error };
        }
        return { success: true, data: result.data };
      }

      case 'getPowerFlowData': {
        if (!sessionId) {
          return { success: false, error: 'sessionId is required' };
        }
        const result = await apiClient.getPowerFlowResults(sessionId, userId, userToken);
        if (!result.success) {
          return { success: false, error: result.error };
        }
        return { success: true, data: result.data };
      }

      // ===========================================
      // FILE OPERATIONS
      // ===========================================

      case 'getUserFiles': {
        const fileType = (args.fileType as 'model' | 'knowledge' | 'sub' | 'mon' | 'con') || 'model';
        if (!['model', 'knowledge', 'sub', 'mon', 'con'].includes(fileType)) {
          return { success: false, error: `Invalid fileType: ${fileType}. Must be one of model | knowledge | sub | mon | con.` };
        }
        const result = await apiClient.getUserFiles(userId, fileType, userToken);
        if (!result.success) {
          return { success: false, error: result.error };
        }
        return { success: true, data: result.data };
      }

      case 'deleteUserFile': {
        const fileType = args.fileType as 'model' | 'knowledge' | 'sub' | 'mon' | 'con';
        const fileName = args.fileName as string;
        if (!fileType || !['model', 'knowledge', 'sub', 'mon', 'con'].includes(fileType)) {
          return { success: false, error: 'fileType is required and must be one of model | knowledge | sub | mon | con.' };
        }
        if (!fileName) {
          return { success: false, error: 'fileName is required' };
        }
        const result = await apiClient.deleteUserFile(fileType, fileName, userId, userToken);
        if (!result.success) {
          return {
            success: false,
            error: result.error,
            data: { errorCode: result.errorCode, status: result.status },
          };
        }
        return { success: true, data: result.data };
      }

      case 'loadStudyFile': {
        if (!sessionId) {
          return { success: false, error: 'sessionId is required (no active session)' };
        }
        const fileType = args.fileType as 'sub' | 'mon' | 'con';
        const fileName = args.fileName as string;
        if (!fileType || !['sub', 'mon', 'con'].includes(fileType)) {
          return { success: false, error: 'fileType is required and must be one of sub | mon | con.' };
        }
        if (!fileName) {
          return { success: false, error: 'fileName is required' };
        }
        const result = await apiClient.loadStudyFile(sessionId, fileType, fileName, userId, userToken);
        if (!result.success) {
          return {
            success: false,
            error: result.error,
            data: { errorCode: result.errorCode, status: result.status },
          };
        }
        // The api-server runs validation inline on load — surface its
        // diagnostics so the LLM knows whether the file is usable.
        return { success: true, data: result.data };
      }

      case 'validateStudyFiles': {
        if (!sessionId) {
          return { success: false, error: 'sessionId is required (no active session)' };
        }
        const result = await apiClient.validateStudyFiles(sessionId, userId, userToken);
        if (!result.success) {
          return {
            success: false,
            error: result.error,
            data: { errorCode: result.errorCode, status: result.status },
          };
        }
        return { success: true, data: result.data };
      }

      case 'uploadUserFile': {
        const fileName = args.fileName as string;
        const fileContent = args.fileContent as string;
        if (!fileName || !fileContent) {
          return { success: false, error: 'fileName and fileContent are required' };
        }
        const result = await apiClient.uploadFile(fileName, fileContent, userId, userToken);
        if (!result.success) {
          return { success: false, error: result.error };
        }
        return { success: true, data: result.data };
      }

      case 'saveSessionToUserFile':
      case 'saveSessionAsUserFile': {
        // These require session info - get it first
        if (!sessionId) {
          return { success: false, error: 'sessionId is required' };
        }
        const sessionInfo = await apiClient.getSession(sessionId, userId, userToken);
        if (!sessionInfo.success) {
          return { success: false, error: sessionInfo.error };
        }
        // Return session data for saving
        return { 
          success: true, 
          data: { 
            message: 'Session data ready for save',
            session: sessionInfo.data,
            fileName: (args.newFileName as string) || (sessionInfo.data as any)?.file_name,
          } 
        };
      }

      // ===========================================
      // GRAPH TRAVERSAL
      // ===========================================

      case 'findShortestPath': {
        if (!sessionId) {
          return { success: false, error: 'sessionId is required' };
        }
        const fromBus = args.fromBus as number;
        const toBus = args.toBus as number;
        if (fromBus == null || toBus == null) {
          return { success: false, error: 'fromBus and toBus are required' };
        }
        const result = await apiClient.findShortestPath(sessionId, fromBus, toBus, userId, userToken);
        if (!result.success) {
          return { success: false, error: result.error };
        }
        return { success: true, data: result.data };
      }

      case 'findNeighbourElements': {
        if (!sessionId) {
          return { success: false, error: 'sessionId is required' };
        }
        const originBus = args.originBus as number;
        const n = args.n as number;
        if (originBus == null || n == null) {
          return { success: false, error: 'originBus and n are required' };
        }
        if (!Number.isInteger(n) || n < 1 || n > 99) {
          return { success: false, error: 'n must be an integer between 1 and 99' };
        }
        const elementTypes = args.elementTypes as string[] | undefined;
        const result = await apiClient.findNeighbourElements(sessionId, originBus, n, elementTypes, userId, userToken);
        if (!result.success) {
          return { success: false, error: result.error };
        }
        return { success: true, data: result.data };
      }

      // ===========================================
      // CONTINGENCY ANALYSIS (async jobs)
      // ===========================================
      // Each arm makes exactly one apiClient call — no polling, sleeping, or
      // retry loops. The per-turn polling guard lives in BrainEngine, not here.

      case 'startContingencyAnalysis': {
        if (!sessionId) {
          return { success: false, error: 'sessionId is required' };
        }
        const settings = (args.settings as Record<string, unknown> | undefined);
        const configOverrides = (args.configOverrides as Record<string, unknown> | undefined);
        const result = await apiClient.startContingencyAnalysis(
          sessionId,
          settings,
          configOverrides,
          userId,
          userToken,
        );
        if (!result.success) {
          // Surface the api-server's machine-readable code so the LLM can
          // distinguish analysis_in_progress / contingency_not_ready / etc.
          return {
            success: false,
            error: result.error,
            data: { errorCode: result.errorCode, status: result.status },
          };
        }
        const job = result.data!;
        return {
          success: true,
          data: {
            jobId: job.id,
            state: job.state,
            progress: job.progress,
            startedAt: job.created_at,
          },
        };
      }

      case 'getContingencyJobStatus': {
        const jobId = typeof args.jobId === 'string' ? args.jobId.trim() : '';
        if (!jobId) {
          return { success: false, error: 'jobId is required' };
        }
        const result = await apiClient.getContingencyJobStatus(jobId, userId, userToken);
        if (!result.success) {
          return {
            success: false,
            error: result.error,
            data: { errorCode: result.errorCode, status: result.status },
          };
        }
        const job = result.data!;
        const elapsedSeconds = Math.max(
          0,
          Math.round((Date.parse(job.updated_at) - Date.parse(job.created_at)) / 1000),
        );
        return {
          success: true,
          data: {
            jobId: job.id,
            state: job.state,
            progress: {
              done: job.progress?.done ?? 0,
              total: job.progress?.total ?? 0,
              fraction: job.progress?.total
                ? Math.round(((job.progress.done ?? 0) / job.progress.total) * 1000) / 1000
                : 0,
              violations: job.progress?.violations,
              detail: job.progress?.detail,
            },
            elapsedSeconds,
            studyResultId: job.study_result_id,
            errorMessage: job.error,
          },
        };
      }

      case 'getContingencyReport': {
        const jobId = typeof args.jobId === 'string' ? args.jobId.trim() : '';
        if (!jobId) {
          return { success: false, error: 'jobId is required' };
        }
        const result = await apiClient.getContingencyReport(jobId, userId, userToken);
        if (!result.success) {
          return {
            success: false,
            error: result.error,
            data: { errorCode: result.errorCode, status: result.status },
          };
        }
        // Reports for large case files can be many MB; sending the entire
        // report.json to the LLM burns tokens for no benefit. Summarize when
        // the payload is over ~64 KB JSON, otherwise pass through verbatim.
        const summarized = summarizeContingencyReport(result.data);
        return { success: true, data: summarized };
      }

      case 'cancelContingencyJob': {
        const jobId = typeof args.jobId === 'string' ? args.jobId.trim() : '';
        if (!jobId) {
          return { success: false, error: 'jobId is required' };
        }
        const result = await apiClient.cancelContingencyJob(jobId, userId, userToken);
        if (result.success) {
          return { success: true, data: { jobId, state: 'cancelled' } };
        }
        // 409 from the api-server means the job is already in a terminal state
        // — that still satisfies the user's intent ("make it stop running").
        if (result.status === 409 || result.errorCode === 'job_already_finished') {
          return {
            success: true,
            data: { jobId, alreadyTerminal: true, message: result.error },
          };
        }
        return {
          success: false,
          error: result.error,
          data: { errorCode: result.errorCode, status: result.status },
        };
      }

      // ===========================================
      // UNKNOWN TOOL
      // ===========================================

      default:
        return {
          success: false,
          error: `Unknown tool: ${name}`,
          hint: 'Check the tool name and try again.',
        };
    }
  } catch (error: any) {
    logger.error('[ToolExecutor] Tool execution failed', error, { name, args });
    return {
      success: false,
      error: error.message || 'Unknown error',
      hint: 'The operation failed unexpectedly. Check the error message.',
    };
  }
}

/**
 * Execute multiple tool calls in sequence
 * Tracks session ID changes across tool calls
 */
export async function executeToolCalls(
  functionCalls: Array<{ name: string; arguments: string; call_id: string }>,
  context?: ToolExecutionContext
): Promise<{
  results: Array<{ call_id: string; result: unknown; error?: string }>;
  sessionId?: string;
}> {
  const results: Array<{ call_id: string; result: unknown; error?: string }> = [];
  
  // Track the current session ID across tool calls
  let currentSessionId = context?.sessionId;

  for (const call of functionCalls) {
    let args: Record<string, unknown> = {};
    try {
      args = JSON.parse(call.arguments);
    } catch {
      results.push({
        call_id: call.call_id,
        result: { success: false, error: 'Invalid JSON arguments' },
        error: 'Invalid JSON arguments',
      });
      continue;
    }

    // Use current session ID if available
    const toolContext: ToolExecutionContext = {
      ...context,
      sessionId: currentSessionId || context?.sessionId,
    };

    const result = await executeMCPTool(call.name, args, toolContext);
    
    // Update session ID if a new session was created
    if (result.sessionId) {
      currentSessionId = result.sessionId;
      logger.info('[ToolExecutor] Session ID updated', { sessionId: currentSessionId });
    }

    results.push({
      call_id: call.call_id,
      result: result.success ? result.data : { success: false, error: result.error, hint: result.hint },
      error: result.success ? undefined : result.error,
    });
  }

  return {
    results,
    sessionId: currentSessionId,
  };
}

export default {
  executeMCPTool,
  executeToolCalls,
};
